config/routes.rb
SocialNetworking::Engine.routes.draw do
  # client interfaces
  get "/profile_page", to: "profile_pages#show", as: :social_networking_profile
  get "/profile_page/:id", to: "profile_pages#show", as: :social_networking_profile_with_id
  get "/profiles_page", to: "profile_pages#index", as: :social_networking_profiles
  get "/profiles_page/participant/:participant_id/page/:page", to: "profile_pages#page"

  # server api
  put "profiles/:id", to: "profiles#update", as: :profile
  resources :profiles, only: [:index, :show]
  resources :participants, only: [:index, :show]
  resources :nudges, only: [:create, :index]
  resources :on_the_mind_statements, only: :create
  resources :goals, only: [:index, :create]
  post "goals/:id", to: "goals#update", as: :goal
  resource :home, only: :show
  resources :profile_answers, only: [:index, :show, :create]
  post "profile_answers/:id", to: "profile_answers#update"
  resources :comments, only: :create
  resources :likes, only: :create
  get "/templates/:path.html" => "templates#page", constraints: { path: /.+/  }
  post "profile_icons", to: "profile_icon#save"
  get "/shared_items/:id/hide", to: "shared_item#hide"
  get "/shared_items/participant/:participant_id/page/:page", to: "shared_item#page"
end

app/models/social_networking/action_item.rb
# frozen_string_literal: true
module SocialNetworking
  # A helper for aggregating "todo" items.
  class ActionItem
    class << self
      attr_writer :source_class_name

      def for(participant)
        return [] if @source_class_name.nil?

        @source_class_name.constantize.for(participant)
      end
    end
  end
end

app/models/social_networking/comment.rb
# frozen_string_literal: true
module SocialNetworking
  # A comment written by a Participant and attached to a piece of content.
  class Comment < ActiveRecord::Base
    belongs_to :participant
    belongs_to :item, polymorphic: true

    validates :participant, :item, :text, presence: true

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
                 .gteq(Time.current.advance(days: -7).beginning_of_day))
    }

    def item_description
      case item_type
      when SocialNetworking::OnTheMindStatement.to_s
        Shareable.new(item).description
      when SocialNetworking::SharedItem.to_s
        if item
          Shareable.new(item.item).description
        else
          Shareable.new(nil).description
        end
      end
    end
  end
end

app/models/social_networking/concerns/membership.rb
# frozen_string_literal: true
module SocialNetworking
  module Concerns
    # adds scops to Membership class
    module Membership
      extend ActiveSupport::Concern
      def comments
        SocialNetworking::Comment.where(participant: participant)
      end

      def likes
        SocialNetworking::Like.where(participant: participant)
      end

      def nudges
        SocialNetworking::Nudge.where(initiator_id: participant)
      end

      def goals
        SocialNetworking::Goal.where(participant: participant)
      end

      def on_the_minds
        SocialNetworking::OnTheMindStatement.where(participant: participant)
      end
    end
  end
end

app/models/social_networking/concerns/participant.rb
# frozen_string_literal: true
module SocialNetworking
  module Concerns
    # adds associations to Participant class
    module Participant
      extend ActiveSupport::Concern

      included do
        has_many :social_networking_comments,
                 class_name: "SocialNetworking::Comment",
                 dependent: :destroy
        has_many :social_networking_goals,
                 class_name: "SocialNetworking::Goal",
                 dependent: :destroy
        has_many :social_networking_likes,
                 class_name: "SocialNetworking::Like",
                 dependent: :destroy
        has_many :initiator_nudges,
                 foreign_key: :initiator_id,
                 class_name: "SocialNetworking::Nudge",
                 dependent: :destroy
        has_many :recipient_nudges,
                 foreign_key: :recipient_id,
                 class_name: "SocialNetworking::Nudge",
                 dependent: :destroy
        has_many :social_networking_on_the_mind_statements,
                 class_name: "SocialNetworking::OnTheMindStatement",
                 dependent: :destroy
        has_one :social_networking_profile,
                class_name: "SocialNetworking::Profile",
                dependent: :destroy

        validates :email, presence: true, if: "contact_preference == 'email'"
        validates :phone_number, presence: true, if: :phone_number?

        private

        def phone_number?
          %w(sms phone).include?(contact_preference)
        end
      end
    end
  end
end

app/models/social_networking/goal.rb
# frozen_string_literal: true
module SocialNetworking
  # Something to be completed by a Participant.
  class Goal < ActiveRecord::Base
    # create a mini DSL for types of Goal actions
    ACTION_TYPES = %w(created completed did_not_complete).freeze
    Actions = Struct.new(*ACTION_TYPES.map(&:to_sym))
                    .new(*(ACTION_TYPES.map { |t| t.tr("_", " ") }))

    belongs_to :participant
    has_many :comments, as: "item"
    has_many :likes, as: "item"

    validates :participant, :description, presence: true
    validate :not_due_in_the_past, on: :create
    validate :due_before_membership_ends, on: :create

    # Within the last day, used for shared item generation
    scope :did_not_complete, (lambda do
      where(deleted_at: nil, completed_at: nil)
      .where(arel_table[:due_on].lt(Time.zone.today))
      .where(arel_table[:due_on].gteq(Time.zone.today - 1.day))
    end)

    def to_serialized
      if due_on
        {
          description: description,
          dueOn: due_on.to_s(:participant_date)
        }
      else
        {}
      end
    end

    def shared_description
      "Goal: #{description}"
    end

    # Necessary for legacy front-end code.
    # rubocop:disable Style/PredicateName
    def is_completed
      completed_at?
    end
    # rubocop:enable Style/PredicateName

    # Necessary for legacy front-end code.
    # rubocop:disable Style/PredicateName
    def is_deleted
      deleted_at?
    end
    # rubocop:enable Style/PredicateName

    def action
      if is_completed
        "Completed"
      elsif due_on && due_on < Time.zone.today
        "Did Not Complete"
      else
        "Created"
      end
    end

    private

    def not_due_in_the_past
      return if due_on.nil? || due_on >= Time.zone.today

      errors.add :due_on, "must not be in the past"
    end

    def due_before_membership_ends
      return if due_on.nil? ||
                participant_id.nil? ||
                participant.active_membership_end_date.nil? ||
                due_on <= participant.active_membership_end_date

      errors.add :due_on, "must be during study enrollment"
    end

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
             .gteq(Time.current.advance(days: -7).beginning_of_day))
    }
  end
end

app/models/social_networking/like.rb
# frozen_string_literal: true
module SocialNetworking
  # A sign of approval of a piece of content by a Participant.
  class Like < ActiveRecord::Base
    belongs_to :participant
    belongs_to :item, polymorphic: true

    validates :participant, :item, presence: true
    # a Participant may only Like an item once
    validates :item_id, uniqueness: { scope: [:item_type, :participant_id] }

    scope :for_today,
          lambda {
            where(
              arel_table[:created_at]
              .gteq(Time.zone.today.beginning_of_day)
              .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day))
            )
          }

    scope :for_week,
          lambda {
            where(arel_table[:created_at]
                    .gteq(Time.current.advance(days: -7).beginning_of_day))
          }

    def item_description
      case item_type
      when "SocialNetworking::OnTheMindStatement"
        Shareable.new(item).description
      when "SocialNetworking::SharedItem"
        if item
          Shareable.new(item.item).description
        else
          Shareable.new(nil).description
        end
      end
    end
  end
end

app/models/social_networking/notification.rb
# frozen_string_literal: true
module SocialNetworking
  # Sends sms or emails to participants.
  class Notification
    include Sms
    attr_reader :current_participant,
                :mailer,
                :recipient,
                :message_body,
                :subject

    def initialize(current_participant:,
                   mailer:,
                   recipient:,
                   message_body:,
                   subject:)
      @current_participant = current_participant
      @mailer = mailer
      @message_body = message_body
      @recipient = recipient
      @subject = subject
    end

    def notify
      return if current_participant == recipient
      if recipient.contact_preference == "email"
        send_email
      else
        begin
          send_sms(recipient, message_body)
        rescue Twilio::REST::RequestError => exception
          Raven
            .capture_message "TWILLIO: failed to notify recipient via SMS",
                             extra: {
                               message: exception.message,
                               phone_number: recipient.try(:phone_number),
                               participant: recipient.try(:id)
                             } if defined?(Raven)
        end
      end
    end

    def send_email
      mailer
        .notify(
          recipient: recipient,
          body: message_body,
          subject: subject
        )
        .deliver_now
    end
  end
end

app/models/social_networking/nudge.rb
# frozen_string_literal: true
module SocialNetworking
  # A form of contact between two Participants.
  class Nudge < ActiveRecord::Base
    belongs_to :initiator,
               class_name: "Participant",
               foreign_key: "initiator_id"
    belongs_to :recipient, class_name: "Participant"
    has_many :comments, as: "item"

    accepts_nested_attributes_for :recipient

    alias_attribute :participant_id, :initiator_id

    validates :initiator, :recipient, presence: true

    def self.search(recipient_id = nil)
      if recipient_id
        select(:initiator_id)
          .where(recipient_id: recipient_id)
          .where("created_at > ?", 1.day.ago)
          .group(:initiator_id)
      else
        all
      end
    end

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
             .gteq(Time.current.advance(days: -7).beginning_of_day))
    }
  end
end

app/models/social_networking/on_the_mind_statement.rb
# frozen_string_literal: true
module SocialNetworking
  # A statement by a Participant to be shared with the Group.
  class OnTheMindStatement < ActiveRecord::Base
    belongs_to :participant
    has_many :comments, as: "item", dependent: :destroy
    has_many :likes, as: "item", dependent: :destroy

    validates :participant, :description, presence: true

    scope :for_today, lambda {
      where(
        "created_at <= ? AND created_at >= ?",
        Time.zone.today.end_of_day,
        Time.zone.today.beginning_of_day
      )
    }

    scope :for_week, lambda {
      where("created_at >= ?", Time.current.advance(days: -7).beginning_of_day)
    }

    def shared_description
      description
    end
  end
end

app/models/social_networking/profile.rb
# frozen_string_literal: true
module SocialNetworking
  # A set of data representing a Social Profile belonging to a Participant.
  class Profile < ActiveRecord::Base
    ACTION_TYPES = %w(created completed).freeze
    Actions = Struct.new(*ACTION_TYPES.map(&:to_sym)).new(*ACTION_TYPES)

    after_create :share_profile

    belongs_to :participant
    has_many :profile_answers,
             class_name: "SocialNetworking::ProfileAnswer",
             foreign_key: :social_networking_profile_id,
             dependent: :destroy
    has_many :comments, as: "item"
    has_many :likes, as: "item"

    validates :participant, presence: true
    validates :participant_id, uniqueness: true

    delegate :latest_action_at, :active_membership_end_date,
             to: :participant

    def self.icon_names
      %w( art bike bolt bookshelf die fashion flower genius
          heart helicopter hourglass keyboard magnifyingglass
          megaphone2 microphone music paintbrush2 plane
          polaroidcamera present recycle scooter shipwheel
          shoeprints star travelerbag ufo umbrella weather )
    end

    def to_serialized
      {}
    end

    def started?
      profile_answers.any?
    end

    def description
      "Welcome, #{user_name}!"
    end

    def shared_description
      "Profile Created: #{participant.display_name}"
    end

    def user_name
      if participant.is_admin
        Rails.application.config.moderating_participant_display_name
      else
        participant.display_name
      end
    end

    private

    def share_profile
      SharedItem.create(
        item: self,
        action_type: Profile::Actions.created
      )
    end
  end
end

app/models/social_networking/profile_answer.rb
# frozen_string_literal: true
module SocialNetworking
  # A question that is posed to participants when a profile is being created or
  # updated.
  class ProfileAnswer < ActiveRecord::Base
    belongs_to :profile,
               class_name: "SocialNetworking::Profile",
               foreign_key: :social_networking_profile_id
    belongs_to :profile_question,
               class_name: "SocialNetworking::ProfileQuestion",
               foreign_key: :social_networking_profile_question_id

    validates :profile, :profile_question, presence: true
    validates :social_networking_profile_question_id, uniqueness: {
      scope: :social_networking_profile_id, message: "has already been answered"
    }
  end
end

app/models/social_networking/profile_question.rb
# frozen_string_literal: true
module SocialNetworking
  # A question that is posed to participants when a profile is being created or
  # updated.
  class ProfileQuestion < ActiveRecord::Base
    belongs_to :group,
               class_name: "ThinkFeelDoEngine::Group",
               foreign_key: :group_id

    has_many :profile_answers,
             class_name: "SocialNetworking::ProfileAnswer",
             foreign_key: :social_networking_profile_question_id,
             dependent: :destroy
  end
end

app/models/social_networking/reports/comment.rb
# frozen_string_literal: true
module SocialNetworking
  module Reports
    # Scenario: a Participant comments on a feed item.
    class Comment
      def self.columns
        %w( participant_id occurred_at item_type text item_participant_id
            item_content )
      end

      def self.all
        Participant.select(:id, :study_id).map do |participant|
          ::SocialNetworking::Comment
            .where(participant_id: participant.id).map do |comment|
              item = (comment.item.try(:item) || comment.item)
              next if item.nil?
              item_participant = Participant
                                 .find_by_id(item.try(:participant_id))

              {
                participant_id: participant.study_id,
                occurred_at: comment.created_at.iso8601,
                item_type: item.class.to_s,
                text: comment.text,
                item_participant_id: item_participant.try(:study_id),
                item_content: comment.item_description
              }
            end
        end.flatten.compact
      end

      def self.to_csv
        ThinkFeelDoEngine::Reports::Reporter.new(self).write_csv
      end
    end
  end
end

app/models/social_networking/reports/goal.rb
# frozen_string_literal: true
module SocialNetworking
  module Reports
    # Scenario: a Participant has a Goal.
    class Goal
      def self.columns
        %w(participant_id created_at due_on is_completed is_deleted description)
      end
      # rubocop:enable Metrics/LineLength

      def self.all
        Participant.select(:id, :study_id).map do |participant|
          ::SocialNetworking::Goal
            .where(participant_id: participant.id).map do |goal|
              {
                participant_id: participant.study_id,
                created_at: goal.created_at.iso8601,
                due_on: goal.due_on ? goal.due_on.iso8601 : "",
                is_completed: goal.is_completed,
                is_deleted: goal.is_deleted,
                description: goal.description
              }
            end
        end.flatten
      end

      def self.to_csv
        ThinkFeelDoEngine::Reports::Reporter.new(self).write_csv
      end
    end
  end
end

app/views/social_networking/application/create_goal.html.erb
<%= stylesheet_link_tag "social_networking/bootstrap_overrides" %>

<div ng-app="socialNetworking">
  <div ng-controller="GoalCtrl as goal">
    <button class="btn btn-link hidden-xs" ng-click="goal.new()" ng-show="goal.inBrowseMode()">+ add a goal</button>

    <form novalidate role="form" name="goalForm" class="row" ng-show="goal.inEntryMode()">
      <div class="form-group col-lg-8 col-md-8">
        <label for="new-goal-description">What is your goal?</label>
        <input type="text" class="form-control" id="new-goal-description" ng-model="goal.description" ng-maxlength="255" required focus-on="new-goal">
        <button class="btn btn-primary" ng-click="goal.save()" ng-disabled="goalForm.$invalid">Save</button>
        <button class="btn btn-default" ng-click="goal.resetForm()">Cancel</button>
      </div>
    </form>

    <ul class="list-group">
      <li ng-repeat="participantGoal in goal.participantGoals | filter:goal.currentFilter | orderBy:'isCompleted'"
          class="list-group-item"
          ng-class="participantGoal.isCompleted ? 'list-group-item-success' : ''">
        <goal />
      </li>
    </ul>

    <nav class="navbar navbar-default navbar-fixed-bottom visible-xs-block" role="navigation">
      <div class="container">
        <div class="row">
          <div class="col-xs-2"><button class="btn btn-link" ng-click="goal.new()">+</button></div>
          <div class="col-xs-2" ng-class="goal.selectedTab === 'all' ? 'active' : ''" ng-click="goal.filter('all'); goal.selectTab('all')"><button class="btn btn-link">All</button></div>
          <div class="col-xs-4" ng-class="goal.selectedTab === 'completed' ? 'active' : ''" ng-click="goal.filter('completed'); goal.selectTab('completed')"><button class="btn btn-link">Completed</button></div>
          <div class="col-xs-4" ng-class="goal.selectedTab === 'deleted' ? 'active' : ''" ng-click="goal.filter('deleted'); goal.selectTab('deleted')"><button class="btn btn-link">Deleted</button></div>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/social_networking/application/feed.html.erb
<%= render "social_networking/shared/nav" %>

<div ng-controller="FeedCtrl as feed">
  <div ng-repeat="item in feed.items">
    <div feed-item></div>
  </div>
</div>

app/views/social_networking/application/goals.html.erb
<%= stylesheet_link_tag "social_networking/bootstrap_overrides" %>

<%= content_for :navbar do %>
  <ul class="nav navbar-nav">
    <li class="active"><%= link_to "Goals", social_networking_goals_path, data: { no_turbolink: true } %></li>
  </ul>
<% end %>

<div ng-app="socialNetworking">
  <div ng-controller="GoalCtrl as goal">
    <div class="row hidden-xs">
      <div class="col-sm-3 col-md-3 col-lg-3">
        <button class="btn btn-link" ng-click="goal.new()" ng-show="goal.inBrowseMode()">+ add a goal</button>
      </div>

      <div class="col-sm-9 col-md-9 col-lg-9">
        <ul class="nav nav-tabs" role="tablist">
          <li ng-class="goal.selectedTab === 'all' ? 'active' : ''"><a href="" ng-click="goal.filter('all'); goal.selectTab('all')">All</a></li>
          <li ng-class="goal.selectedTab === 'completed' ? 'active' : ''"><a href="" ng-click="goal.filter('completed'); goal.selectTab('completed')">Completed</a></li>
          <li ng-class="goal.selectedTab === 'deleted' ? 'active' : ''"><a href="" ng-click="goal.filter('deleted'); goal.selectTab('deleted')">Deleted</a></li>
        </ul>
      </div>
    </div>

    <form novalidate role="form" name="goalForm" class="row" ng-show="goal.inEntryMode()">
      <div class="form-group col-lg-8 col-md-8">
        <label for="new-goal-description">What is your goal?</label>
        <input type="text" class="form-control" id="new-goal-description" ng-model="goal.description" ng-maxlength="255" required focus-on="new-goal">
      </div>

      <div class="form-group col-lg-8 col-md-8">
        <label>When do you want it completed?</label>
        <div class="radio">
          <label>
            <input type="radio" name="due-on" ng-model="goal.dueOn" value=""> no specific date
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="due-on" ng-model="goal.dueOn" value="{{ goal.dateInNWeeks(1) }}"> end of one week
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="due-on" ng-model="goal.dueOn" value="{{ goal.dateInNWeeks(2) }}"> end of 2 weeks
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="due-on" ng-model="goal.dueOn" value="{{ goal.dateInNWeeks(4) }}"> end of 4 weeks
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="due-on" ng-model="goal.dueOn" value="{{ goal.dateAtEndOfTrial() }}"> end of the trial
          </label>
        </div>
      </div>

      <div class="form-group col-lg-8 col-md-8">
        <button class="btn btn-primary" ng-click="goal.save()" ng-disabled="goalForm.$invalid">Save</button>
        <button class="btn btn-default" ng-click="goal.resetForm()">Cancel</button>
      </div>
    </form>

    <ul class="list-group">
      <li ng-repeat="participantGoal in goal.participantGoals | filter:goal.currentFilter | orderBy:'isCompleted'"
          class="list-group-item"
          id="goal-{{ participantGoal.id }}"
          ng-class="participantGoal.isCompleted ? 'list-group-item-success' : ''">
        <label>
          <input ng-disabled="participantGoal.isDeleted" type="checkbox" ng-model="participantGoal.isCompleted" ng-change="goal.toggleComplete(participantGoal)"> {{ participantGoal.description }}
        </label>

        <button ng-if="!participantGoal.isDeleted" class="btn btn-link pull-right delete" ng-click="goal.toggleDeleted(participantGoal)"><i class="fa fa-trash-o text-danger"></i></button>
        <button ng-if="participantGoal.isDeleted" class="btn btn-link pull-right restore" ng-click="goal.toggleDeleted(participantGoal)"><i class="fa fa-undo"></i></button>
      </li>
    </ul>

    <nav class="navbar navbar-default navbar-fixed-bottom visible-xs-block" role="navigation">
      <div class="container">
        <div class="row">
          <div class="col-xs-2"><button class="btn btn-link" ng-click="goal.new()">+</button></div>
          <div class="col-xs-2" ng-class="goal.selectedTab === 'all' ? 'active' : ''" ng-click="goal.filter('all'); goal.selectTab('all')"><button class="btn btn-link">All</button></div>
          <div class="col-xs-4" ng-class="goal.selectedTab === 'completed' ? 'active' : ''" ng-click="goal.filter('completed'); goal.selectTab('completed')"><button class="btn btn-link">Completed</button></div>
          <div class="col-xs-4" ng-class="goal.selectedTab === 'deleted' ? 'active' : ''" ng-click="goal.filter('deleted'); goal.selectTab('deleted')"><button class="btn btn-link">Deleted</button></div>
        </div>
      </div>
    </nav>
  </div>
</div>

<!-- bootstrap Angular app with current participant study end date -->
<script>
  angular.module('socialNetworking').value('participantStudyEndDate', '<%= current_participant.active_membership_end_date %>');
</script>

app/views/social_networking/application/profile.html.erb
<%= stylesheet_link_tag "social_networking/bootstrap_overrides" %>

<%= render "social_networking/shared/nav" %>

<div ng-controller="ProfileCtrl as profile">
  <div profile-status></div>
  <a href="" ng-click="profile.nudge()">Nudge</a>
  <a href="" ng-click="profile.edit()">Edit my profile</a>
  <dl>
    <dt ng-repeat-start="r in profile.responses">{{ r.question }}</dt>
    <dd ng-repeat-end>{{ r.text }}</dd>
  </dl>
</div>

<!-- bootstrap Angular app with current participant id -->
<script>
  angular.module('socialNetworking').value('participantId', <%= current_participant.id %>);
</script>

app/views/social_networking/application/profiles.html.erb
<%= stylesheet_link_tag "social_networking/bootstrap_overrides" %>

<%= render "social_networking/shared/nav" %>

<div ng-controller="ProfilesCtrl as profiles">
  <div ng-repeat="profile in profiles.members">
    <div profile-status></div>
  </div>
</div>