config/routes.rb
SocialNetworking::Engine.routes.draw do
  # client interfaces
  get "/profile_page", to: "profile_pages#show", as: :social_networking_profile
  get "/profile_page/:id", to: "profile_pages#show", as: :social_networking_profile_with_id
  get "/profiles_page", to: "profile_pages#index", as: :social_networking_profiles
  get "/profiles_page/participant/:participant_id/page/:page", to: "profile_pages#page"

  # server api
  put "profiles/:id", to: "profiles#update", as: :profile
  resources :profiles, only: [:index, :show]
  resources :participants, only: [:index, :show]
  resources :nudges, only: [:create, :index]
  resources :on_the_mind_statements, only: :create
  resources :goals, only: [:index, :create]
  post "goals/:id", to: "goals#update", as: :goal
  resource :home, only: :show
  resources :profile_answers, only: [:index, :show, :create]
  post "profile_answers/:id", to: "profile_answers#update"
  resources :comments, only: :create
  resources :likes, only: :create
  get "/templates/:path.html" => "templates#page", constraints: { path: /.+/  }
  post "profile_icons", to: "profile_icon#save"
  get "/shared_items/:id/hide", to: "shared_item#hide"
  get "/shared_items/participant/:participant_id/page/:page", to: "shared_item#page"
end

app/models/social_networking/action_item.rb
# frozen_string_literal: true
module SocialNetworking
  # A helper for aggregating "todo" items.
  class ActionItem
    class << self
      attr_writer :source_class_name

      def for(participant)
        return [] if @source_class_name.nil?

        @source_class_name.constantize.for(participant)
      end
    end
  end
end

app/models/social_networking/comment.rb
# frozen_string_literal: true
module SocialNetworking
  # A comment written by a Participant and attached to a piece of content.
  class Comment < ActiveRecord::Base
    belongs_to :participant
    belongs_to :item, polymorphic: true

    validates :participant, :item, :text, presence: true

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
                 .gteq(Time.current.advance(days: -7).beginning_of_day))
    }

    def item_description
      case item_type
      when SocialNetworking::OnTheMindStatement.to_s
        Shareable.new(item).description
      when SocialNetworking::SharedItem.to_s
        if item
          Shareable.new(item.item).description
        else
          Shareable.new(nil).description
        end
      end
    end
  end
end

app/models/social_networking/concerns/membership.rb
# frozen_string_literal: true
module SocialNetworking
  module Concerns
    # adds scops to Membership class
    module Membership
      extend ActiveSupport::Concern
      def comments
        SocialNetworking::Comment.where(participant: participant)
      end

      def likes
        SocialNetworking::Like.where(participant: participant)
      end

      def nudges
        SocialNetworking::Nudge.where(initiator_id: participant)
      end

      def goals
        SocialNetworking::Goal.where(participant: participant)
      end

      def on_the_minds
        SocialNetworking::OnTheMindStatement.where(participant: participant)
      end
    end
  end
end

app/models/social_networking/concerns/participant.rb
# frozen_string_literal: true
module SocialNetworking
  module Concerns
    # adds associations to Participant class
    module Participant
      extend ActiveSupport::Concern

      included do
        has_many :social_networking_comments,
                 class_name: "SocialNetworking::Comment",
                 dependent: :destroy
        has_many :social_networking_goals,
                 class_name: "SocialNetworking::Goal",
                 dependent: :destroy
        has_many :social_networking_likes,
                 class_name: "SocialNetworking::Like",
                 dependent: :destroy
        has_many :initiator_nudges,
                 foreign_key: :initiator_id,
                 class_name: "SocialNetworking::Nudge",
                 dependent: :destroy
        has_many :recipient_nudges,
                 foreign_key: :recipient_id,
                 class_name: "SocialNetworking::Nudge",
                 dependent: :destroy
        has_many :social_networking_on_the_mind_statements,
                 class_name: "SocialNetworking::OnTheMindStatement",
                 dependent: :destroy
        has_one :social_networking_profile,
                class_name: "SocialNetworking::Profile",
                dependent: :destroy

        validates :email, presence: true, if: "contact_preference == 'email'"
        validates :phone_number, presence: true, if: :phone_number?

        private

        def phone_number?
          %w(sms phone).include?(contact_preference)
        end
      end
    end
  end
end

app/models/social_networking/goal.rb
# frozen_string_literal: true
module SocialNetworking
  # Something to be completed by a Participant.
  class Goal < ActiveRecord::Base
    # create a mini DSL for types of Goal actions
    ACTION_TYPES = %w(created completed did_not_complete).freeze
    Actions = Struct.new(*ACTION_TYPES.map(&:to_sym))
                    .new(*(ACTION_TYPES.map { |t| t.tr("_", " ") }))

    belongs_to :participant
    has_many :comments, as: "item"
    has_many :likes, as: "item"

    validates :participant, :description, presence: true
    validate :not_due_in_the_past, on: :create
    validate :due_before_membership_ends, on: :create

    # Within the last day, used for shared item generation
    scope :did_not_complete, (lambda do
      where(deleted_at: nil, completed_at: nil)
      .where(arel_table[:due_on].lt(Time.zone.today))
      .where(arel_table[:due_on].gteq(Time.zone.today - 1.day))
    end)

    def to_serialized
      if due_on
        {
          description: description,
          dueOn: due_on.to_s(:participant_date)
        }
      else
        {}
      end
    end

    def shared_description
      "Goal: #{description}"
    end

    # Necessary for legacy front-end code.
    # rubocop:disable Style/PredicateName
    def is_completed
      completed_at?
    end
    # rubocop:enable Style/PredicateName

    # Necessary for legacy front-end code.
    # rubocop:disable Style/PredicateName
    def is_deleted
      deleted_at?
    end
    # rubocop:enable Style/PredicateName

    def action
      if is_completed
        "Completed"
      elsif due_on && due_on < Time.zone.today
        "Did Not Complete"
      else
        "Created"
      end
    end

    private

    def not_due_in_the_past
      return if due_on.nil? || due_on >= Time.zone.today

      errors.add :due_on, "must not be in the past"
    end

    def due_before_membership_ends
      return if due_on.nil? ||
                participant_id.nil? ||
                participant.active_membership_end_date.nil? ||
                due_on <= participant.active_membership_end_date

      errors.add :due_on, "must be during study enrollment"
    end

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
             .gteq(Time.current.advance(days: -7).beginning_of_day))
    }
  end
end

app/models/social_networking/like.rb
# frozen_string_literal: true
module SocialNetworking
  # A sign of approval of a piece of content by a Participant.
  class Like < ActiveRecord::Base
    belongs_to :participant
    belongs_to :item, polymorphic: true

    validates :participant, :item, presence: true
    # a Participant may only Like an item once
    validates :item_id, uniqueness: { scope: [:item_type, :participant_id] }

    scope :for_today,
          lambda {
            where(
              arel_table[:created_at]
              .gteq(Time.zone.today.beginning_of_day)
              .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day))
            )
          }

    scope :for_week,
          lambda {
            where(arel_table[:created_at]
                    .gteq(Time.current.advance(days: -7).beginning_of_day))
          }

    def item_description
      case item_type
      when "SocialNetworking::OnTheMindStatement"
        Shareable.new(item).description
      when "SocialNetworking::SharedItem"
        if item
          Shareable.new(item.item).description
        else
          Shareable.new(nil).description
        end
      end
    end
  end
end

app/models/social_networking/notification.rb
# frozen_string_literal: true
module SocialNetworking
  # Sends sms or emails to participants.
  class Notification
    include Sms
    attr_reader :current_participant,
                :mailer,
                :recipient,
                :message_body,
                :subject

    def initialize(current_participant:,
                   mailer:,
                   recipient:,
                   message_body:,
                   subject:)
      @current_participant = current_participant
      @mailer = mailer
      @message_body = message_body
      @recipient = recipient
      @subject = subject
    end

    def notify
      return if current_participant == recipient
      if recipient.contact_preference == "email"
        send_email
      else
        begin
          send_sms(recipient, message_body)
        rescue Twilio::REST::RequestError => exception
          Raven
            .capture_message "TWILLIO: failed to notify recipient via SMS",
                             extra: {
                               message: exception.message,
                               phone_number: recipient.try(:phone_number),
                               participant: recipient.try(:id)
                             } if defined?(Raven)
        end
      end
    end

    def send_email
      mailer
        .notify(
          recipient: recipient,
          body: message_body,
          subject: subject
        )
        .deliver_now
    end
  end
end

app/models/social_networking/nudge.rb
# frozen_string_literal: true
module SocialNetworking
  # A form of contact between two Participants.
  class Nudge < ActiveRecord::Base
    belongs_to :initiator,
               class_name: "Participant",
               foreign_key: "initiator_id"
    belongs_to :recipient, class_name: "Participant"
    has_many :comments, as: "item"

    accepts_nested_attributes_for :recipient

    alias_attribute :participant_id, :initiator_id

    validates :initiator, :recipient, presence: true

    def self.search(recipient_id = nil)
      if recipient_id
        select(:initiator_id)
          .where(recipient_id: recipient_id)
          .where("created_at > ?", 1.day.ago)
          .group(:initiator_id)
      else
        all
      end
    end

    scope :for_today, lambda {
      where(arel_table[:created_at]
                .gteq(Time.zone.today.beginning_of_day)
                .and(arel_table[:created_at].lteq(Time.zone.today.end_of_day)))
    }

    scope :for_week, lambda {
      where(arel_table[:created_at]
             .gteq(Time.current.advance(days: -7).beginning_of_day))
    }
  end
end

app/models/social_networking/on_the_mind_statement.rb
# frozen_string_literal: true
module SocialNetworking
  # A statement by a Participant to be shared with the Group.
  class OnTheMindStatement < ActiveRecord::Base
    belongs_to :participant
    has_many :comments, as: "item", dependent: :destroy
    has_many :likes, as: "item", dependent: :destroy

    validates :participant, :description, presence: true

    scope :for_today, lambda {
      where(
        "created_at <= ? AND created_at >= ?",
        Time.zone.today.end_of_day,
        Time.zone.today.beginning_of_day
      )
    }

    scope :for_week, lambda {
      where("created_at >= ?", Time.current.advance(days: -7).beginning_of_day)
    }

    def shared_description
      description
    end
  end
end

app/models/social_networking/profile.rb
# frozen_string_literal: true
module SocialNetworking
  # A set of data representing a Social Profile belonging to a Participant.
  class Profile < ActiveRecord::Base
    ACTION_TYPES = %w(created completed).freeze
    Actions = Struct.new(*ACTION_TYPES.map(&:to_sym)).new(*ACTION_TYPES)

    after_create :share_profile

    belongs_to :participant
    has_many :profile_answers,
             class_name: "SocialNetworking::ProfileAnswer",
             foreign_key: :social_networking_profile_id,
             dependent: :destroy
    has_many :comments, as: "item"
    has_many :likes, as: "item"

    validates :participant, presence: true
    validates :participant_id, uniqueness: true

    delegate :latest_action_at, :active_membership_end_date,
             to: :participant

    def self.icon_names
      %w( art bike bolt bookshelf die fashion flower genius
          heart helicopter hourglass keyboard magnifyingglass
          megaphone2 microphone music paintbrush2 plane
          polaroidcamera present recycle scooter shipwheel
          shoeprints star travelerbag ufo umbrella weather )
    end

    def to_serialized
      {}
    end

    def started?
      profile_answers.any?
    end

    def description
      "Welcome, #{user_name}!"
    end

    def shared_description
      "Profile Created: #{participant.display_name}"
    end

    def user_name
      if participant.is_admin
        Rails.application.config.moderating_participant_display_name
      else
        participant.display_name
      end
    end

    private

    def share_profile
      SharedItem.create(
        item: self,
        action_type: Profile::Actions.created
      )
    end
  end
end

app/models/social_networking/profile_answer.rb
# frozen_string_literal: true
module SocialNetworking
  # A question that is posed to participants when a profile is being created or
  # updated.
  class ProfileAnswer < ActiveRecord::Base
    belongs_to :profile,
               class_name: "SocialNetworking::Profile",
               foreign_key: :social_networking_profile_id
    belongs_to :profile_question,
               class_name: "SocialNetworking::ProfileQuestion",
               foreign_key: :social_networking_profile_question_id

    validates :profile, :profile_question, presence: true
    validates :social_networking_profile_question_id, uniqueness: {
      scope: :social_networking_profile_id, message: "has already been answered"
    }
  end
end

app/models/social_networking/profile_question.rb
# frozen_string_literal: true
module SocialNetworking
  # A question that is posed to participants when a profile is being created or
  # updated.
  class ProfileQuestion < ActiveRecord::Base
    belongs_to :group,
               class_name: "ThinkFeelDoEngine::Group",
               foreign_key: :group_id

    has_many :profile_answers,
             class_name: "SocialNetworking::ProfileAnswer",
             foreign_key: :social_networking_profile_question_id,
             dependent: :destroy
  end
end

app/models/social_networking/reports/comment.rb
# frozen_string_literal: true
module SocialNetworking
  module Reports
    # Scenario: a Participant comments on a feed item.
    class Comment
      def self.columns
        %w( participant_id occurred_at item_type text item_participant_id
            item_content )
      end

      def self.all
        Participant.select(:id, :study_id).map do |participant|
          ::SocialNetworking::Comment
            .where(participant_id: participant.id).map do |comment|
              item = (comment.item.try(:item) || comment.item)
              next if item.nil?
              item_participant = Participant
                                 .find_by_id(item.try(:participant_id))

              {
                participant_id: participant.study_id,
                occurred_at: comment.created_at.iso8601,
                item_type: item.class.to_s,
                text: comment.text,
                item_participant_id: item_participant.try(:study_id),
                item_content: comment.item_description
              }
            end
        end.flatten.compact
      end

      def self.to_csv
        ThinkFeelDoEngine::Reports::Reporter.new(self).write_csv
      end
    end
  end
end

app/models/social_networking/reports/goal.rb
# frozen_string_literal: true
module SocialNetworking
  module Reports
    # Scenario: a Participant has a Goal.
    class Goal
      def self.columns
        %w(participant_id created_at due_on is_completed is_deleted description)
      end
      # rubocop:enable Metrics/LineLength

      def self.all
        Participant.select(:id, :study_id).map do |participant|
          ::SocialNetworking::Goal
            .where(participant_id: participant.id).map do |goal|
              {
                participant_id: participant.study_id,
                created_at: goal.created_at.iso8601,
                due_on: goal.due_on ? goal.due_on.iso8601 : "",
                is_completed: goal.is_completed,
                is_deleted: goal.is_deleted,
                description: goal.description
              }
            end
        end.flatten
      end

      def self.to_csv
        ThinkFeelDoEngine::Reports::Reporter.new(self).write_csv
      end
    end
  end
end

app/views/social_networking/profile_pages/_profile_questions.html.erb
<% panel_class = panel_class || "default" %>
<% if current_participant.id == @profile.participant_id %>
  <% unless @nudging_display_names.empty? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <%= @nudging_display_names.to_sentence %> nudged you!
    </div>
  <% end %>
  <div ng-controller="ProfileQuestionsCtrl as profileQuestions">
    <div ng-controller="ProfileAnswerCtrl as answer">
      <h3 ng-hide="answer.ifAnswered(profileQuestions.questions)">
        Fill out your profile so other group members can get to know you!
      </h3>
      <div class="panel panel-<%= panel_class %>">
        <div class="panel-heading">
          <strong class="panel-title">
            Profile
            &middot;
            <small>Please be sure to click 'Save' after each response.</small>
          </strong>
        </div>
        <div class="panel-body">
          <div ng-repeat="question in profileQuestions.questions | orderBy:'order'"
               class="panel panel-<%= panel_class %>"
               id="question-{{ question.id }}"
               ng-init="answer.storeAnswer(<%= @profile.id %>, question.id, answer)">
            <div class="panel-heading">
              <label class="panel-title" for="new-answer-description-{{ question.id }}">
                {{ question.question_text }}
              </label>
            </div>
            <div class="panel-body">
              <form novalidate role="form" name="answerForm" class="row" ng-show="answer._answerStates[question.id].editable">
                <input type="hidden" name="profile_question_id" value="{{ question.id }}" ng-if="answer.answerModels[question.id].id === null">
                <input type="hidden" name="profile_id" value="<%= @profile.id %>" ng-if="answer.answerModels[question.id].id === null">
                <input type="hidden" name="id" ng-if="answer.answerModels[question.id].id !== null">

                <div class="form-group col-lg-8 col-md-8">
                  <input
                    class="form-control"
                    id="new-answer-description-{{question.id}}"
                    ng-focus="answer.showCharLimit('#new-answer-description-' + question.id)"
                    ng-maxlength="answer.textMaxLength"
                    ng-model="answer.answerModels[question.id].answer_text"
                    type="text">
                </div>

                <div class="form-group col-lg-8 col-md-8">
                  <button class="btn btn-primary" ng-click="answer.save(<%= @profile.id %>, question.id, answer)">Save</button>
                </div>
              </form>
            <div ng-show="!answer._answerStates[question.id].editable">
              <div class="media-body media-middle">
                <span>
                  {{ answer.answerModels[question.id].answer_text }}
                </span>
              </div>

              <div class="form-group media-right media-middle">
                <button class="btn btn-link edit" ng-click="answer.edit(question.id)"><i class="fa fa-pencil"></i></button>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div ng-controller="ProfileQuestionsCtrl as profileQuestions">
    <div ng-controller="ProfileAnswerCtrl as answer">
      <div class="panel panel-<%= panel_class %>">
        <div class="panel-heading"><strong class="panel-title">Profile</strong></div>
        <div class="panel-body">
          <div ng-repeat="question in profileQuestions.questions | orderBy:'order'" class="panel panel-<%= panel_class %>" ng-init="answer.storeAnswer(<%= @profile.id %>, question.id, answer)">
            <div class="panel-heading"><strong class="panel-title">{{ question.question_text }}</strong></div>
            <div class="panel-body">
              {{ answer.answerModels[question.id].answer_text }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/social_networking/profile_pages/index.html.erb
<div ng-controller="ProfilesCtrl as profiles" ng-cloak>
  <div ng-repeat="profile in profiles.members">
    <div class="row profile-participant">
      <p>
        User: 
        <a href="<%= social_networking_profile_path %>/{{ profile.id }}" data-no-turbolink="true">
        <img ng-src="{{ profile.iconSrc }}">
          {{ profile.username }}
        </a>
      </p>
      <p ng-class="profile.isAdmin ? 'invisible' : ''">
        Last seen: {{ profile.latestAction | timeFromNow }}
      </p>
    </div>
    <dl>
      <dt ng-repeat-start="r in profile.responses">{{ r.question }}</dt>
      <dd ng-repeat-end>{{ r.text }}</dd>
    </dl>
  </div>
</div>

<!-- bootstrap Angular app with current participant id -->
<script>
  angular.module('socialNetworking')
    .value('participantId', <%= current_participant.id %>)
    .value('profileId', <%= @profile.id %>);
</script>

app/views/social_networking/profile_pages/show.html.erb
<div ng-controller="ProfileCtrl as profile" ng-cloak>
  <div class="modal-container">
    <div class="modal fade" id="profile-icon-selection" tabindex="-1" role="dialog" aria-labelledby="icon-modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 id="icon-modal">
              <div ng-if="<%=@profile.icon_name.nil?%>">Start creating your profile by choosing a profile icon:</div>
              <div ng-if="<%=!@profile.icon_name.nil?%>">Choose a new profile icon:</div>
            </h3>
            <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true" id="icon-selection-button">×</button>
          </div>

          <div class="modal-body">
            <% @profile_icons.each_with_index do |icon_name, index| %>
              <% if 0 == index % 6 %><div class="row"><% end %>
              <div ng-click="profile.updateProfileIcon('<%= icon_name %>')" class="col-lg-2 col-sm-4 col-xs-4 text-center icon-selection">
                <%= image_tag 'social_networking/profile_icon_'+ icon_name +'.png' %>
              </div>
              <% if 5 == index % 6 || index + 1 == @profile_icons.size %></div><% end %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="text-center" id="profile-box">
    <div class="profile-box-content profile-box-border">
      <% if current_participant.id == @profile.participant_id %>
        <a href="" data-toggle="modal" data-target="#profile-icon-selection" id="profile-icon-selector">
      <% end %>

      <img ng-src="{{ profile.profile.iconSrc }}" id="profile-icon">

      <% if current_participant.id == @profile.participant_id %>
        </a>
      <% end %>

      <div class="profiles-username">
        <h3>{{ profile.profile.username }}</h3>
      </div>
    </div>

    <div class="profiles-last-online profile-box-border">
      <h3 ng-class="profile.profile.isAdmin ? 'invisible' : ''">
        Last seen: {{ profile.profile.latestAction | timeFromNow }}
      </h3>
    </div>

    <% if current_participant.id != @profile.participant_id %>
      <div class="profiles-nudge profile-box-border well well-lg">
        <a class="btn btn-lg btn-primary" href="" id="nudge-link" ng-click="profile.nudge(<%= @profile.participant_id %>)">Nudge</a>
        <br><span>{{ profile.nudgeAlert }}</span>
      </div>
    <% end %>
  </div>

  <div ng-repeat="alert in profile.getAlerts()" class="alert {{alert.cssClass}}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" ng-click="profile.removeAlert(alert)">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{alert.message}}
  </div>
</div>

<%= render partial: "profile_questions", locals: { nudging_display_names: @nudging_display_names } %>

<div ng-controller="HomeCtrl as home">
  <%= render "social_networking/shared/comment_form" %>
  <ul class="list-group"
    id="infinite-feed"
    infinite-scroll="home.getMore()"
    infinite-scroll-immediate-check="true"
    infinite-scroll-disabled="false">
    <%= render "social_networking/shared/infinite_feed" %>
  </ul>
</div>

<form accept-charset="UTF-8" action="/social_networking/profile_icons" id="icon_change" method="post">
  <input id="profile_id" name="profile[profile_id]" type="hidden" value="<%= @profile.id %>"/>
  <input id="icon_name" name="profile[icon_name]" type="hidden" value="<%= @profile.icon_name %>"/>
</form>

<script>
  angular.module('socialNetworking')
          .value('currentParticipantId', <%= current_participant.id %>)
          .value('participantId', <%= @profile.participant_id %>)
          .value('profileId', <%= @profile.id %>)
          .value('ProfileQuestions', <%= @profile_questions.to_json.html_safe %>)
          .value('actionItems', [])
          .value('memberProfiles', <%= @member_profiles.to_json.html_safe %>)
          .value('feedItems', [])
          .value('noticesEnabled', <%= Rails.configuration.enable_notices %>)
          .value('noticeUtility', Notice)
          .value('resource', 'profiles_page');

  function displayProfileIcons() {
    if (<%= @profile.participant_id == current_participant.id %> && <%= @profile.icon_name.nil? %>) {
      $('#profile-icon-selection').modal('show');
    }
  }

  $(document).on("page:change", displayProfileIcons);
</script>